"""Add missing columns to sync_jobs table

Revision ID: 3422c731986c
Revises: 95016917d7af
Create Date: 2025-05-28 22:23:56.148828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3422c731986c'
down_revision: Union[str, None] = '95016917d7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawled_pages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('crawled_pages', 'connector_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('crawled_pages', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('crawled_pages', 'depth',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('crawled_pages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_crawled_pages_content_hash', table_name='crawled_pages')
    op.drop_index('idx_crawled_pages_content_type', table_name='crawled_pages')
    op.drop_index('idx_crawled_pages_depth', table_name='crawled_pages')
    op.create_index('idx_crawled_pages_last_crawled', 'crawled_pages', ['last_crawled'], unique=False)
    op.create_unique_constraint('uq_crawled_pages_org_connector_url', 'crawled_pages', ['organization_id', 'connector_id', 'url_hash'])
    op.add_column('sync_jobs', sa.Column('triggered_by', sa.UUID(), nullable=True))
    op.add_column('sync_jobs', sa.Column('last_activity_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('sync_jobs', sa.Column('total_items', sa.Integer(), nullable=True))
    op.add_column('sync_jobs', sa.Column('processed_items', sa.Integer(), nullable=True))
    op.add_column('sync_jobs', sa.Column('progress_percentage', sa.Float(), nullable=True))
    op.drop_index('idx_sync_jobs_connector_status', table_name='sync_jobs')
    op.create_index('idx_sync_jobs_status_created', 'sync_jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_sync_jobs_triggered_by', 'sync_jobs', ['triggered_by'], unique=False)
    op.create_foreign_key(None, 'sync_jobs', 'users', ['triggered_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_jobs', type_='foreignkey')
    op.drop_index('idx_sync_jobs_triggered_by', table_name='sync_jobs')
    op.drop_index('idx_sync_jobs_status_created', table_name='sync_jobs')
    op.create_index('idx_sync_jobs_connector_status', 'sync_jobs', ['connector_id', 'status'], unique=False)
    op.drop_column('sync_jobs', 'progress_percentage')
    op.drop_column('sync_jobs', 'processed_items')
    op.drop_column('sync_jobs', 'total_items')
    op.drop_column('sync_jobs', 'last_activity_at')
    op.drop_column('sync_jobs', 'triggered_by')
    op.drop_constraint('uq_crawled_pages_org_connector_url', 'crawled_pages', type_='unique')
    op.drop_index('idx_crawled_pages_last_crawled', table_name='crawled_pages')
    op.create_index('idx_crawled_pages_depth', 'crawled_pages', ['depth'], unique=False)
    op.create_index('idx_crawled_pages_content_type', 'crawled_pages', ['content_type'], unique=False)
    op.create_index('idx_crawled_pages_content_hash', 'crawled_pages', ['content_hash'], unique=False)
    op.alter_column('crawled_pages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('crawled_pages', 'depth',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('crawled_pages', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'success'::character varying"),
               existing_nullable=False)
    op.alter_column('crawled_pages', 'connector_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('crawled_pages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
